#!/usr/bin/env bash
# Copyright (C) 2014, Alexey Pavlov
#   mailto:alexpux@gmail.com
# This file is part of Minimal SYStem version 2.
#   https://sourceforge.net/p/msys2/wiki/MSYS2%20installation/
# File: start

#cmd //c start "${@//&/^&}"
# add "" to open file which has space in file name
# need to quote path \"file name\"
cmd //c start "" "${@//&/^&}"

